version: '3'

services:
  redis:
    image: "redis"
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

  redis_exporter:
    build: .
    command: ['redis_exporter', '--log-level', 'DEBUG']
    stop_signal: SIGINT
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/metrics"]
    depends_on:
      - redis
    ports:
      - 9999:9999

volumes:
  redis_data:
